# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70a4443a82062e62cbeadb881b5aeda0a973f178d9acccd4ede35e06646c25a16fe46d60f73a63a857e6646c27835803fd9c6cead489500172dbfb58e072fdaa

test:
  secret_key_base: d55368378b36d7ae1911ac606c55df210b9beab598bebd97ab569230647408ab82315ccf8d7acc4a5859235f4e20ecf01907ad87f86e1c544bbddb0d8aea7899

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
